# Generated by Django 5.2.17 on 2026-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='Informática', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='00000000000000', max_length=20),
            preserve_default=False,
        ),
    ]
